version: "3"

services:
  lnd_bitcore:
    image: btcpayserver/lnd:0.4.2.0.1
    container_name: btcpayserver_lnd_bitcore
    restart: unless-stopped
    environment:
      LND_CHAIN: "btx"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        bitcore.node=bitcored
        bitcored.rpchost=bitcored:43782
        bitcored.zmqpath=tcp://bitcored:28332
        externalip=${BTCPAY_HOST}:9736
        alias=${LIGHTNING_ALIAS}
        noencryptwallet=1
        notls=1
    ports:
      - "9736:9735"
    expose:
      - "8080"
      - "9736"
    volumes:
      - "lnd_bitcore_datadir:/data"
      - "bitcore_datadir:/deps/.bitcore"
      - "nbxplorer_datadir:/root/.nbxplorer"
    links:
      - nbxplorer
      - bitcored

  btcpayserver:
    environment:
      BTCPAY_BTXLIGHTNING: "type=lnd-rest;server=http://lnd_bitcore:8080/;macaroonfilepath=/etc/lnd_bitcore/admin.macaroon;allowinsecure=true"
    volumes:
      - "lnd_bitcore_datadir:/etc/lnd_bitcore"
    links:
      - lnd_bitcore

  bitcored:
    environment:
      BITCOIN_EXTRA_ARGS: |
        zmqpubrawtx=tcp://0.0.0.0:28332
        zmqpubrawblock=tcp://0.0.0.0:28332
    expose:
      - "28332"

volumes:
  lnd_bitcore_datadir:
